FROM node:18.4.0-alpine

ARG API_HOST=localhost
ARG API_PORT=8080

# Try to make sure auto reload is enabled on code change
ENV CHOKIDAR_USEPOLLING true
ENV CHOKIDAR_INTERVAL 2000

# If you have low performing Hardware, enable this for hot reload without fast refresh:
#ARG FAST_REFRESH=false

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app files
COPY . ./

# install app dependencies
RUN npm ci --legacy-peer-deps

# replace default proxy with actual API HOST / PORT
RUN sed -i "s/localhost:8080/${API_HOST}:${API_PORT}/g" package.json

# start app
CMD npm start
