# pull official base image
FROM node:13.12.0-alpine

ARG API_HOST=localhost
ARG API_PORT=8080

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app files
COPY . ./

# install app dependencies
RUN npm ci

# replace default proxy with actual API HOST / PORT
RUN sed -i "s/localhost:8080/${API_HOST}:${API_PORT}/g" package.json

# start app
CMD ["npm", "start"]
