version: "3.2"
services:
  api:
    image: eep-portal/api:${TAG}
    environment:
      RPC_HOST: master
      RPC_PORT: ${RPC_PORT}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      SWAGGER_BASEPATH: /prod
    links:
      - master
    ports:
      - "8080:${API_PORT}"

  master:
    image: eep-portal/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      EXTERNAL_IP: ${EXTERNAL_IP}
    volumes:
      - /tmp/bcMasterVolume:/root/.multichain
    ports:
      - "7447:7447"

  testapi:
    image: eep-portal/api:${TAG}
    environment:
      RPC_HOST: testmaster
      RPC_PORT: ${RPC_PORT}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      ROOT_SECRET: ${ROOT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      SWAGGER_BASEPATH: /test
    links:
      - testmaster
    ports:
      - "8081:${API_PORT}"

  testmaster:
    image: eep-portal/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      EXTERNAL_IP: ${EXTERNAL_IP}
    volumes:
      - /tmp/bcTestMasterVolume:/root/.multichain
    ports:
      - "7448:7447"

  frontend:
    image: eep-portal/frontend:${TAG}
    environment:
      PROD_API_HOST: api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: testapi
      TEST_API_PORT: ${API_PORT}
      EXPORT_PORT: 8888
      EXPORT_HOST: export
    depends_on:
      - api
      - testapi
      - export
    ports:
      - "80:80"

  export:
    image: eep-portal/excel-export:${TAG}
    environment:
      PROD_API_HOST: api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: testapi
      TEST_API_PORT: ${API_PORT}
      PORT: 8888
    depends_on:
      - api
      - testapi
    ports:
      - "8888:8888"
