# This file intended to be merged into the master-node.yml inside the same directory
version: "3.2"
services:
  provision-prod:
    image: eep-portal/provisioning:${TAG}
    command: ["npm", "start"]
    environment:
      API_HOST: api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    links:
      - api

  provision-test:
    image: eep-portal/provisioning:${TAG}
    command: ["npm", "start"]
    environment:
      API_HOST: testapi
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    links:
      - testapi
