version: "3"
services:
  provisioning:
    image: trubudget/provisioning:${TAG}
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      API_PROTOCOL: ${API_PROTOCOL}
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
      PROVISIONING_TYPE: ${PROVISIONING_TYPE}
      LOG_LEVEL: ${PROVISIONING_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      PROVISIONING_SERVICE_USER: ${PROVISIONING_SERVICE_USER}
      PROVISIONING_SERVICE_PASSWORD: ${PROVISIONING_SERVICE_PASSWORD}
