version: "3"

services:
  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    # volume for persisting data
    # volumes:
    #   - /minioVolume:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  storage-service:
    depends_on:
      - minio
      - alpha-api