version: "3"
services:
  frontend-collector:
    image: trubudget/frontend-collector:${TAG}
    environment:
      LOGGER_PORT: ${LOGGER_PORT}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOGGING_SERVICE_CACHE_DURATION: ${LOGGING_SERVICE_CACHE_DURATION}
      NODE_ENV: ${ENVIRONMENT}
    ports:
      - "${LOGGER_PORT}:${LOGGER_PORT}"
