version: "3.2"
services:
  api:
    image: trubudget/api:${TAG}
    environment:
      MULTICHAIN_RPC_HOST: alpha
      MULTICHAIN_RPC_PORT: ${MULTICHAIN_RPC_PORT}
      MULTICHAIN_RPC_PASSWORD: ${MULTICHAIN_RPC_PASSWORD}
      PORT: ${API_PORT}
      ORGANIZATION: KfW
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      SWAGGER_BASEPATH: /test
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    shm_size: 1024M
    ports:
      - "${API_PORT}:${API_PORT}" # Mapping the nginx port
    links:
      - alpha
      - minio

  alpha:
    image: trubudget/blockchain:${TAG}
    environment:
      MULTICHAIN_RPC_PORT: ${MULTICHAIN_RPC_PORT}
      MULTICHAIN_RPC_PASSWORD: ${MULTICHAIN_RPC_PASSWORD}
      ORGANIZATION: KfW
    volumes:
      - /alphaVolume:/root/.multichain

  frontend:
    image: trubudget/frontend:${TAG}
    ports:
      - "80:80" # Mapping the nginx port
    environment:
      PROD_API_HOST: api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: api
      TEST_API_PORT: ${API_PORT}
      EXPORT_PORT: ${EXPORT_PORT}
      EXPORT_HOST: export
      REACT_APP_EXPORT_SERVICE_ENABLED: "true"
    links:
      - api
      - export
    logging:
      driver: none

  provisioning:
    image: trubudget/provisioning:${TAG}
    environment:
      API_HOST: api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: TEST
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: KfW
    links:
      - api
    depends_on:
      - api
      - alpha
    command: ["npm", "start"]

  export:
    image: trubudget/excel-export-service:${TAG}
    environment:
      PROD_API_HOST: api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: api
      TEST_API_PORT: ${API_PORT}
      PORT: ${EXPORT_PORT}
    depends_on:
      - api
    ports:
      - "${EXPORT_PORT}:${EXPORT_PORT}"

  cypress:
    build:
      context: "../../e2e-test"
    links:
      - frontend
      - api
      - export
      - provisioning
    environment:
      CYPRESS_ROOT_SECRET: ${ROOT_SECRET}
      CYPRESS_BASE_URL: http://frontend
    depends_on:
      - frontend
      - alpha
      - api
      - export
      - provisioning
    shm_size: 1024M
    volumes:
      - ../../e2e-test/cypress:/cypress
    command: |
      /bin/bash -c "
        while
        ping -c1 provisioning &>/dev/null
        do
        sleep 5
        done
        echo 'Provisioning finished!'
        $$(npm bin)/cypress run -- -b chrome
      "

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    volumes:
      - ../../minio/data:/data
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
