version: "3"
services:
  master-node:
    build: ../../blockchain
    environment:
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
    # volumes:
    #   - /tmp/bcMasterVolume:/root/.multichain
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - "8085:8085"
      - "7447:7447"
    networks: 
      - "trubudgetnetwork"

  master-api:
    build: ../../api
    environment:
      APP_NAME: Trubudget
      API_HOST: master-api
      PORT: ${API_PORT}
      NODE_LOCATION_LAT: "30.11"
      NODE_LOCATION_LNG: "4.68"
      NODE_COUNTRY: Brasil
      NODE_DESCRIPTION: UmbrellaCorp
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: master-node
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
      MINIO_ENDPOINT: nginx
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: ["npm", "run", "dev"]
    links:
      - minio1
      - nginx
    volumes:
      - "../../api/src:/home/node/src:delegated"
    ports:
      - ${API_PORT}:${API_PORT}
      - "9230:9229"
    networks: 
      - "trubudgetnetwork"
    depends_on:
      - master-node

  provisioning:
    build:
      context: ../../provisioning
    command: ["npm", "start"]
    environment:
      API_HOST: master-api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    networks: 
    - "trubudgetnetwork"
    depends_on:
      - master-api

  minio1:
    image: minio/minio
    volumes:
      - ../../minio/data:/data
    expose:
      - "9000"
    networks: 
      - "trubudgetnetwork"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ../../minio/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    networks: 
      - "trubudgetnetwork"
    depends_on:
      - minio1

networks:
  trubudgetnetwork:
