export const amazonasFundProject = {
  displayName: "Amazonas Fund 53",
  description: "Projects in 2017",
  status: "open",
  amount: "32000000",
  assignee: "jdoe",
  currency: "BRL",
  permissions: {
    "project.viewDetails": ["mstein", "jxavier"],
    "project.viewSummary": ["mstein", "jxavier"],
    "project.assign": ["mstein", "jxavier"],
    "project.intent.listPermissions": ["mstein", "jxavier"],
    "project.intent.grantPermission": ["mstein", "jxavier"],
    "project.intent.revokePermission": ["mstein", "jxavier"],
  },
  subprojects: [
    {
      displayName: "Consultancy studies",
      description: "No description.",
      status: "closed",
      amount: "500000",
      currency: "BRL",
      assignee: "jdoe",
      permissions: {
        "subproject.viewSummary": ["jxavier"],
        "subproject.viewDetails": ["jxavier"],
      },
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          status: "closed",
          assignee: "jdoe",
          amount: 500000,
          currency: "BRL",
          amountType: "allocated",
        },
        {
          displayName: "Execution monitoring",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Payment advance installment",
          status: "closed",
          assignee: "jdoe",
          amount: 136000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Payment interim installment",
          status: "closed",
          assignee: "jdoe",
          amount: 136000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Payment final installment",
          status: "closed",
          assignee: "jdoe",
          amount: 118000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Completion subproject",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
      ],
    },
    {
      displayName: "Consultancy supervision",
      description: "No description.",
      status: "open",
      amount: "750000",
      currency: "BRL",
      assignee: "jdoe",
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          assignee: "jdoe",
          amount: 720000,
          currency: "BRL",
          amountType: "allocated",
        },
        {
          displayName: "Execution monitoring",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Payment advance installment",
          assignee: "jdoe",
          amount: 400000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Payment interim installment",
          assignee: "jdoe",
          amount: 172000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Payment final installment",
          assignee: "jdoe",
          amount: 148000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Completion subproject",
          assignee: "jdoe",
          amountType: "N/A",
        },
      ],
    },
    {
      displayName: "Construction lot 1",
      description: "No description.",
      amount: "1750000",
      currency: "BRL",
      assignee: "jdoe",
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          assignee: "jdoe",
          amount: 1680000,
          currency: "BRL",
          amountType: "allocated",
        },
        {
          displayName: "Execution monitoring",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Payment advance installment",
          assignee: "jdoe",
          amount: 336000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Payment interim installment",
          assignee: "jdoe",
          amount: 1176000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Payment final installment",
          assignee: "jdoe",
          amount: 168000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Completion subproject",
          assignee: "jdoe",
          amountType: "N/A",
        },
      ],
    },
    {
      displayName: "Construction lot 2",
      description: "No description.",
      amount: "2500000",
      currency: "BRL",
      assignee: "jdoe",
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          assignee: "jdoe",
          amount: 1680000,
          currency: "BRL",
          amountType: "allocated",
        },
        {
          displayName: "Execution monitoring",
          assignee: "jdoe",
          amountType: "N/A",
        },
      ],
    },
    {
      displayName: "Furniture",
      description: "No description.",
      amount: "500000",
      currency: "BRL",
      assignee: "jdoe",
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          assignee: "jdoe",
          amount: 300000,
          currency: "BRL",
          amountType: "allocated",
        },
        {
          displayName: "Execution monitoring",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Payment advance installment",
          assignee: "jdoe",
          amount: 100000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Payment interim installment",
          assignee: "jdoe",
          amount: 100000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Payment final installment",
          assignee: "jdoe",
          amount: 100000,
          currency: "BRL",
          amountType: "disbursed",
        },
        {
          displayName: "Completion subproject",
          assignee: "jdoe",
          amountType: "N/A",
        },
      ],
    },
  ],
};

export const closeProjectTest = {
  displayName: "project.close test project",
  description: "project.close test data",
  status: "open",
  amount: "9999",
  assignee: "mstein",
  currency: "EUR",
  permissions: {
    "project.viewDetails": ["mstein"],
    "project.viewSummary": ["mstein"],
    "project.close": ["mstein"],
    "project.intent.listPermissions": ["mstein"],
    "project.intent.grantPermission": ["mstein"],
    "project.intent.revokePermission": ["mstein"],
  },
  subprojects: [
    {
      displayName: "Subproject A",
      description: "No description.",
      status: "closed",
      amount: "1000",
      currency: "EUR",
      assignee: "mstein",
      permissions: {
        "subproject.viewSummary": ["mstein"],
        "subproject.viewDetails": ["mstein"],
        "subproject.close": ["mstein"],
      },
      workflows: [],
    },
    {
      displayName: "Subproject B",
      description: "Open and not visible to mstein",
      status: "open",
      amount: "1000",
      currency: "EUR",
      assignee: "jdoe",
      permissions: {
        "subproject.viewSummary": ["jdoe"],
        "subproject.viewDetails": ["jdoe"],
        "subproject.close": ["jdoe"],
      },
      workflows: [],
    },
  ],
};

export const schoolProject = {
  displayName: "Primary School Project",
  description: "Projects in 2018",
  status: "open",
  amount: "30000000",
  assignee: "jdoe",
  currency: "EUR",
  permissions: {
    "project.viewDetails": ["mstein", "jxavier"],
    "project.viewSummary": ["mstein", "jxavier"],
    "project.assign": ["mstein", "jxavier"],
    "project.intent.listPermissions": ["mstein", "jxavier"],
    "project.intent.grantPermission": ["mstein", "jxavier"],
    "project.intent.revokePermission": ["mstein", "jxavier"],
  },
  subprojects: [
    {
      displayName: "Design studies",
      description: "No description.",
      status: "closed",
      amount: "500000",
      currency: "EUR",
      assignee: "jdoe",
      permissions: {
        "subproject.viewSummary": ["jxavier"],
        "subproject.viewDetails": ["jxavier"],
      },
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          status: "closed",
          assignee: "jdoe",
          amount: 500000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "First installment",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Progress report",
          status: "closed",
          assignee: "jdoe",
          amount: 100000,
          currency: "EUR",
          amountType: "disbursed",
        },
        {
          displayName: "Payment interim installment",
          status: "closed",
          assignee: "jdoe",
          amount: 100000,
          currency: "EUR",
          amountType: "disbursed",
        },
        {
          displayName: "Payment final installment",
          status: "closed",
          assignee: "jdoe",
          amount: 300000,
          currency: "EUR",
          amountType: "disbursed",
        },
      ],
    },
    {
      displayName: "Consultancy supervision",
      description: "No description.",
      status: "open",
      amount: "1500000",
      currency: "EUR",
      assignee: "jdoe",
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          assignee: "jdoe",
          amount: 1500000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "First installment",
          assignee: "jdoe",
          amount: 500000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "Payment interim installment",
          assignee: "jdoe",
          amount: 500000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "Progress report",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Payment final installment",
          assignee: "jdoe",
          amount: 500000,
          currency: "EUR",
          amountType: "allocated",
        },
      ],
    },
    {
      displayName: "Construction lot 1",
      description: "No description.",
      amount: "15000000",
      currency: "EUR",
      assignee: "jdoe",
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          assignee: "jdoe",
          amount: 15000000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "First installment",
          assignee: "jdoe",
          amount: 5000000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "Progress report",
          assignee: "jdoe",
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "Payment final installment",
          assignee: "jdoe",
          amount: 10000000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "Completion subproject",
          assignee: "jdoe",
          amountType: "N/A",
        },
      ],
    },
    {
      displayName: "Construction lot 2",
      description: "No description.",
      amount: "8000000",
      currency: "EUR",
      assignee: "jdoe",
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          assignee: "jdoe",
          amount: 8000000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "First installment",
          assignee: "jdoe",
          amount: 3000000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "Progress report",
          assignee: "jdoe",
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "Payment final installment",
          assignee: "jdoe",
          amount: 5000000,
          currency: "EUR",
          amountType: "allocated",
        },
      ],
    },
    {
      displayName: "Equipment",
      description: "No description.",
      amount: "3000000",
      currency: "EUR",
      assignee: "jdoe",
      workflows: [
        {
          displayName: "Budget allocation",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender publication",
          status: "closed",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Tender evaluation",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Contract signature",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "First installment",
          assignee: "jdoe",
          amount: 1500000,
          currency: "EUR",
          amountType: "allocated",
        },
        {
          displayName: "Progress report",
          assignee: "jdoe",
          amountType: "N/A",
        },
        {
          displayName: "Payment final installment",
          assignee: "jdoe",
          amount: 1500000,
          currency: "EUR",
          amountType: "allocated",
        },
      ],
    },
  ],
};
