---
extends:
  - airbnb-base
  - prettier
env:
  node: true
  mocha: true
  es6: true
parser: "@babel/eslint-parser"
parserOptions:
  sourceType: module
  requireConfigFile: false
  ecmaVersion: 9
  ecmaFeatures:
    modules: true
rules:
  generator-star-spacing:
    - 2
    - before: true
      after: true
  no-shadow: 0
  import/no-unresolved: 0
  import/extensions: 0
  require-yield: 0
  no-param-reassign: 0
  comma-dangle: 0
  no-underscore-dangle: 0
  no-control-regex: 0
  no-undef: 2
  linebreak-style: 0
  arrow-body-style: 0
  ## temporarily overriden below
  # import/no-extraneous-dependencies:
  #   - 2
  #   - devDependencies: true
  func-names: 0
  no-unused-expressions: 0
  ## temporarily overriden below
  # prefer-arrow-callback: 1
  ## temporarily overriden below
  # no-use-before-define:
  #   - 2
  #   - functions: false
  space-before-function-paren: 0
  ## temporarily overriden below
  # max-len:
  #   - 2
  #   - 120
  #   - 2
  strict:
    - 2
    - global
  ## temporarily overriden below
  # arrow-parens:
  #   - 2
  #   - always

  ## TEMPORARY OVERRIDES
  ## most of these are turned on by default and overrides can be deleted

  ## should be left turned off, reports false positives for TS
  ## no-unused-vars: 0
  no-unused-vars: 0

  # no-restricted-syntax airbnb override to allow ForOfStatement
  no-restricted-syntax:
    - error
    - ForInStatement
    - LabeledStatement
    - WithStatement

  # disallow require globally, allow require for joi inline
  import/first: 0
  import/order: 0

  ## import/prefer-default-export: 0
  import/prefer-default-export: 0

  ## import/no-extraneous-dependencies but check lodash.isempty imports/require - separate PR
  import/no-extraneous-dependencies: 0

  ## import/no-duplicates: 2 check
  import/no-duplicates: 0

  # import/no-cycle: 2 check if possible to fix
  import/no-cycle: 0

  ## import/export: 2 and check (separate PR?)
  import/export: 0

  ## import/no-useless-path-segments: 2 autofixable
  import/no-useless-path-segments: 0

  ## no-prototype-builtins: 2
  ## use Object.prototype.hasOwnProperty.call
  no-prototype-builtins: 0

  ## spaced-comment: 2 autofixable
  spaced-comment: 0

  ## no-lonely-if: 2 almost autofixable
  no-lonely-if: 0

  ## prefer-destructuring: 2 autofixable
  prefer-destructuring: 0

  ## does not recognize ForOf loops
  ## turn the rule on and add inline overrides
  no-continue: 0

  ## no-buffer-constructor: 2
  no-buffer-constructor: 0

  ## consistent-return can stay turned off, little value in TS
  consistent-return: 0

  ## global isNaN added to exceptions for the rule
  ## Number.isNaN may give different results
  no-restricted-globals:
    - 0
    - isNaN

  ## https://eslint.org/docs/rules/no-await-in-loop
  ## In many cases the iterations of a loop are not actually independent of each-other.
  ## For example, the output of one iteration might be used as the input to another.
  ## Or, loops may be used to retry asynchronous operations that were unsuccessful.
  ## Or, loops may be used to prevent your code from sending an excessive amount of requests in parallel.
  ## In such cases it makes sense to use await within a loop and it is recommended to disable the rule
  ## via a standard ESLint disable comment.
  no-await-in-loop: 0

  ## await on return is redundant
  ## no-return-await: 2
  no-return-await: 0

  ## turn on and inline override
  no-console: 0

  ## no-else-return: 2
  ## autofixable
  no-else-return: 0

  ## rule violations can be resolved with formatting or inline overrides
  max-len: 0

  ## wrap case clauses with lexical declaration in blocks { }
  ## no-case-declarations: 2
  no-case-declarations: 0

  ## autofixable
  ## arrow-parens: 2
  arrow-parens: 0

  ## let's keep this turned off, explicit return helps with understanding of functional flow
  no-useless-return: 0

  ## default-case: 2
  ## throwing errors should be put inside default case
  default-case: 0

  ## object-shorthand: 2
  ## { a } instead of { a: a }
  object-shorthand: 0

  ## string templates instead of concatenation
  prefer-template: 0

  ## autofixable a += b instead of a = a + b
  operator-assignment: 0

  ## use const if variable is not reassigned
  prefer-const: 0

  ## += 1 instead of ++
  no-plusplus: 0

  ## enable rule and override inline
  no-cond-assign: 0

  ## autofixable
  no-irregular-whitespace: 0

  ## https://eslint.org/docs/rules/no-async-promise-executor
  ## The executor function can also be an async function. However, this is usually a mistake
  ## if not, inline override
  ## we have one such instance: return new Promise<RpcResponse>(async (resolve, reject) => ...
  no-async-promise-executor: 0

  ## autofixable
  ## a ? true : false    ->      !!a
  no-unneeded-ternary: 0

  ## nested ternary expressions are terrible, it would be better to refactor in separate PR
  no-nested-ternary: 0

  ## global-require: 2
  ## inline override where desired
  global-require: 0

  ## prefer-arrow-callback: 2
  prefer-arrow-callback: 0

  ## autofixable
  "quotes":
    - 2
    - "double"

  ## this should be fixed in code, that's why i put it here not inline
  no-use-before-define: 0

  import/no-dynamic-require: 0
  no-constant-condition: 0
