#!/bin/sh
# K8S LongRunning KeepAlive script.
# Deals with the fact that exec API call times out if nothing 
# happens on the shell -- so we ensure something happens...

while :; do sleep 5; echo -n ' ' >&2; done &
PROC_ID=$!
"$@"
ret=$?
kill "$PROC_ID"
exit $ret

# use for anaysis if needed:
#
#if [[ $ret -eq 0 ]]
#then
#  echo "Successfully ran [ $@ ]"
#else
#  echo "Error: Command [ $@ ] returned $ret"
#  exit $ret
#fi
