version: "3.2"
services:
  blockchain:
    # image: trubudget/blockchain:latest
    build:
      context: ../blockchain
    environment:
      MULTICHAIN_RPC_PORT: ${MULTICHAIN_RPC_PORT}
      MULTICHAIN_RPC_PASSWORD: ${MULTICHAIN_RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
    ports:
      - "8000:${MULTICHAIN_RPC_PORT}"
      - "8085:8085"

  api:
    # image: trubudget/api:latest
    build:
      context: ../api
    environment:
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      MULTICHAIN_RPC_HOST: ${MULTICHAIN_RPC_HOST}
      MULTICHAIN_RPC_PORT: ${MULTICHAIN_RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      MULTICHAIN_RPC_PASSWORD: ${MULTICHAIN_RPC_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:${API_PORT}"
    links:
      - blockchain

  # Provision the node with some test data to check out the excel export feature
  provisioning:
    image: trubudget/provisioning:latest
    command: ["npm", "start"]
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      PROVISIONING_TYPE: ${PROVISIONING_TYPE}
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    links:
      - api

  frontend:
    # image: trubudget/frontend:latest
    build:
      context: ../frontend
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      REACT_APP_EXPORT_SERVICE_ENABLED: ${REACT_APP_EXPORT_SERVICE_ENABLED}
      EXPORT_HOST: ${EXPORT_HOST}
      EXPORT_PORT: ${EXPORT_PORT}
    links:
      - export
      - api
    ports:
      - "81:80" # Mapping the nginx port

  export:
    build:
      context: .
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      PORT: ${EXPORT_PORT}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${ACCESS_CONTROL_ALLOW_ORIGIN}
      JWT_SECRET: ${JWT_SECRET}
      MODE: DEBUG
    depends_on:
      - api
    ports:
      - "8888:${EXPORT_PORT}"
