{
 "title": "TruBudget Logging Dashboard",
 "tags": [
  "logging",
  "loki",
  "trubudget"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  { "title": "Details for $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Count of Logs",
   "type": "stat",
   "description": "Total Count of logs in namespace $namespace",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count of Error Logs",
   "type": "stat",
   "description": "Logs with errors in namespace $namespace",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\"} |= \"error\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "gauge",
   "description": "Error Percentage in $namespace",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\"} |~ \"error\")[$__interval])) * 100 / sum(count_over_time(({namespace=\"$namespace\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Details for $namespace and $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Total Count of Logs",
   "type": "stat",
   "description": "Total Count of logs in namespace $namespace and pod $pod",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", pod=\"$pod\"})[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Count of Error Logs",
   "type": "stat",
   "description": "Logs with errors in namespace $namespace and pod $pod",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", pod=\"$pod\"} |= \"error\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "gauge",
   "description": "Error Percentage in $namespace and $pod",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", pod=\"$pod\"} |~ \"error\")[$__interval])) * 100 / sum(count_over_time(({namespace=\"$namespace\", pod=\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage",
   "type": "gauge",
   "description": "Percentage of logs containing \"$searchable_pattern\"",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", pod=\"$pod\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({namespace=\"$namespace\", pod=\"$pod\"})[$__interval]))"
    }
   ]
  },
  { "title": "Live logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Live Logs in $pod",
   "type": "logs",
   "description": "Logs for namespace $namespace and pod $pod, containing pattern $searchable_pattern",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=\"$pod\"} |~ \"(?i)$searchable_pattern\" ",
     "legendFormat": "Logs for namespace $namespace and pod $pod"
    }
   ]
  }
 ]
}