apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Values.global.branch }}
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: helm
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "api.name" . }}
      release: {{ .Release.Name }}
      service: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ template "api.name" . }}
        release: {{ .Release.Name }}
        service: {{ .Chart.Name }}
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: {{ .Values.global.branch }}
        app.kubernetes.io/component: api
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- range $key, $value := .Values.api.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.api.resources.memRequest }}
            cpu: {{ .Values.api.resources.cpuRequest }}
          limits:
            memory: {{ .Values.api.resources.memLimit }}
            cpu: {{ .Values.api.resources.cpuLimit }}
        livenessProbe:
          httpGet:
            path: /api/liveness
            port: {{ .Values.api.env.PORT }}
          initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/readiness
            port: {{ .Values.api.env.PORT }}
          initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
          periodSeconds: 10
          timeoutSeconds: 10

