---
extends:
  - airbnb-typescript/base
  - prettier
env:
  node: true
  mocha: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  project: "./tsconfig.json"
  sourceType: module
rules:
  ## temporarily overriden below
  # "@typescript-eslint/quotes":
  #   - 2
  #   - "double"
  #   - "avoidEscape": true
  "@typescript-eslint/no-unused-vars": 0
  generator-star-spacing:
    - 2
    - before: true
      after: true
  no-shadow: 0
  import/no-unresolved: 0
  import/extensions: 0
  require-yield: 0
  no-param-reassign: 0
  comma-dangle: 0
  no-underscore-dangle: 0
  no-control-regex: 0
  ## temporarily overriden below
  # import/no-extraneous-dependencies:
  #   - 2
  #   - devDependencies: true
  func-names: 0
  no-unused-expressions: 0
  ## temporarily overriden below
  # prefer-arrow-callback: 1
  ## temporarily overriden below
  # no-use-before-define:
  #   - 2
  #   - functions: false
  space-before-function-paren: 0
  ## temporarily overriden below
  # max-len:
  #   - 2
  #   - 120
  #   - 2
  strict:
    - 2
    - global
  ## temporarily overriden below
  # arrow-parens:
  #   - 2
  #   - always

  # TEMPORARY OVERRIDES

  no-unused-vars: 0
  # no-restricted-syntax airbnb override to allow ForOfStatement
  no-restricted-syntax:
    - error
    - ForInStatement
    - LabeledStatement
    - WithStatement

  import/first: 0
  import/order: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
  import/no-duplicates: 0
  import/no-cycle: 0
  import/export: 0
  import/no-useless-path-segments: 0
  no-prototype-builtins: 0

  spaced-comment: 0
  no-lonely-if: 0
  no-continue: 0
  no-use-before-define: 0
  prefer-destructuring: 0
  no-buffer-constructor: 0
  consistent-return: 0
  no-restricted-globals:
    - 0
    - isNaN
  no-await-in-loop: 0
  no-return-await: 0
  no-console: 0
  no-else-return: 0
  max-len: 0
  no-case-declarations: 0
  arrow-parens: 0
  no-useless-return: 0
  default-case: 0
  object-shorthand: 0
  prefer-template: 0
  operator-assignment: 0
  prefer-const: 0
  no-plusplus: 0
  no-cond-assign: 0
  no-irregular-whitespace: 0
  no-return-assign: 0
  no-async-promise-executor: 0
  max-classes-per-file: 0 # only one file - RpcClient.ts
  no-unneeded-ternary: 0
  no-nested-ternary: 0
  global-require: 0
  prefer-arrow-callback: 0

  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/no-use-before-define":
    - 0
    # - 2
    # - functions: false
  "@typescript-eslint/no-shadow": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/quotes": 0
  "@typescript-eslint/no-throw-literal": 0
  "@typescript-eslint/no-unused-vars-experimental":
    - 0
    # - 2
    # - ignoreArgsIfArgsAfterAreUsed: true
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/ban-types": 0
  # @typescript-eslint/indent disabled because it messes with formatting
  "@typescript-eslint/indent": 0
  "@typescript-eslint/naming-convention": 0
  "@typescript-eslint/comma-dangle": 0
  "@typescript-eslint/semi": 0
  "@typescript-eslint/no-unused-expressions": 0
  "@typescript-eslint/lines-between-class-members": 0
