name: Audit CI

on: 
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:

  audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        project: [frontend,api,blockchain,provisioning,e2e-test,excel-export,email-notification]
        
    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Audit project ${{ matrix.project }}
        run: npm audit --audit-level=high
